Repository FRONTENDSCHOOL10/5jorago-vanilla-project, pull requests merged in 2024-07, with the labels that each got.

#21 Feature: 배너 컴포넌트 마크업, 스타일링
  node_modules/.vite/deps/_metadata.json
  src/assets/baekpacker_img.webp
  src/assets/baekpacker_logo.webp
  src/components/article/_article.scss
  src/components/article/article.js
  src/components/article/index.html
  src/styles/scss/_function.scss
  src/styles/scss/_index.scss
  src/styles/scss/_mixins.scss
  src/styles/scss/_reset.scss
  src/styles/scss/_variable.scss
Labels: ✏️ markup

#23 Docs: 폴더 생성, 파일 생성
  src/components/article/_article.scss
  src/styles/scss/_article.scss
  src/styles/scss/_index.scss
  src/styles/scss/_mixins.scss
  src/styles/scss/_variables.scss
  src/styles/style.scss
Labels: 📁 documentation

#36 Feature: 배너 컴포넌트 수정 및 파일 추가
  src/assets/baekpacker_img.webp
  src/assets/baekpacker_logo.webp
  src/components/article/_article.scss
  src/components/article/article.js
  src/components/banner/_banner.scss
  src/components/banner/banner.js
  src/components/banner/index.html
  src/main.js
  src/styles/scss/_index.scss
  src/styles/scss/_mixins.scss
  src/styles/scss/_reset.scss
Labels: 📁 documentation, ✏️ markup

#47 Feat: 메인페이지 카드 컴포넌트 2번 마크업, 스타일링
  src/assets/poster-1.png
  src/components/card-2/_card-2.scss
  src/components/card-2/card-2.js
  src/components/card-2/index.html
Labels: 📁 documentation, ✏️ markup

#61 Fix: crad-4컴포넌트 반응형으로 수정
  src/assets/Vertical_2.png
  src/assets/Vertical_3.png
  src/components/card-4/_card-4.scss
  src/components/card-4/index.html
Labels: 🛠️ enhancement, 🖌️css styling

#71 Feat: card-4.js에 템플릿 추가
  package-lock.json
  package.json
  src/components/card-4/card-4.js
Labels: 🛠️ enhancement

#82 Feat:회원가입 페이지 제작
  src/components/input/_input.scss
  src/components/input/input.js
  src/pages/signup/_signup.scss
  src/pages/signup/index.html
  src/pages/signup/signup.js
Labels: ✏️ markup, 🖌️css styling

#81 Style: 랜딩 페이지 마크업 및 스타일 수정, 랜딩 버튼 컴포넌트 생성
  index.html
  main.js
  src/assets/landing-logo.png
  src/components/header/l-header.js
  src/components/rendingbutton/_rendingbutton.scss
  src/components/rendingbutton/rendingbutton.js
  src/styles/style.scss
Labels: 🛠️ enhancement, ✏️ markup, 🖌️css styling

#85 Style: footer 컴포넌트 로고 경로 변수화
  src/components/footer/footer.js
Labels: 🖌️css styling

#86 Feat: 서치 페이지 마크업 및 서치 컴포넌트 뿌리기
  src/components/search/search.js
  src/pages/search/_search.scss
  src/pages/search/index.html
  src/pages/search/search.js
Labels: ✏️ markup, 🖌️css styling

#87 Feature/main swiper
  docs/assets/backgroundimg_1-67FD3PK3.png
  docs/assets/footer-kQhptZPP.js
  docs/assets/gradation-img-Y-J4zsZX.png
  docs/assets/home-wBTjTcx8.js
  docs/assets/home-xDJeSzb9.css
  docs/assets/landing_lovecatcher-eBCxlEgo.png
  docs/assets/main-gHSc-aL2.js
  docs/assets/main-r6OW7QjZ.css
  docs/assets/modulepreload-polyfill-9p4a8sJU.js
  docs/assets/treasureHunt-do5y24OJ.png
  docs/index.html
  docs/src/pages/detail/index.html
  docs/src/pages/login/index.html
  docs/src/pages/main/index.html
  docs/src/pages/search/index.html
  docs/src/pages/signup/index.html
  docs/vite.svg
  src/assets/banner.png
  src/assets/event_ex.png
  src/assets/posterEx.png
  src/assets/postermovie.png
  src/components/banner/_banner.scss
  src/components/banner/banner.js
  src/components/card-1/card-1.js
  src/components/card-2/card-2.js
  src/components/card-2/index.html
  src/components/card-4/_card-4.scss
  src/components/card-4/card-4.js
  src/components/card-4/index.html
  src/components/header/_header.scss
  src/components/header/header.js
  src/pages/main/_main.scss
  src/pages/main/index.html
  src/pages/main/main.js
Labels: ✏️ markup, 🖌️css styling

#91 Refactor: 이미지 경로 코드 수정
  src/components/card-2/card-2.js
  src/components/card-4/card-4.js
Labels: 🛠️ enhancement

#94 Fix: header hover 시 아이콘 이미지 경로 수정
  src/components/header/_header.scss
Labels: 🛠️ enhancement

#99 Fix: 에셋파일 경로 변경에 따른 컴포넌트 이미지 경로 변경
  src/components/banner/banner.js
  src/components/card-1/card-1.js
  src/components/card-2/card-2.js
  src/components/card-4/card-4.js
  src/components/footer/footer.js
  src/components/header/header.js
  src/components/header/l-header.js
  src/components/rendingbutton/rendingbutton.js
Labels: 📁 documentation, 🛠️ enhancement

#102 Feat: search 페이지
  src/components/search/_search.scss
  src/components/search/index.html
  src/components/search/search.js
  src/pages/search/_search.scss
  src/pages/search/index.html
  src/pages/search/search.js
Labels: ✏️ markup, 🖌️css styling

#100 Refator:card 3번 컴포넌트 리팩토링
  src/components/card-3/_card-3.scss
  src/components/card-3/card-3.html
  src/components/card-3/card-3.js
Labels: ☑️ compleated, 🖌️css styling

#107 Feat: 메인 페이지 스와이퍼 구현
  src/components/banner/_banner.scss
  src/components/card-2/_card-2.scss
  src/components/card-2/card-2.js
  src/components/card-4/_card-4.scss
  src/pages/main/_main.scss
  src/pages/main/index.html
  src/pages/main/index.js
  src/pages/main/main.js
  src/styles/pages/main/_footer.scss
  src/styles/pages/main/_promo.scss
  src/styles/pages/main/_section.scss
  src/styles/pages/main/_swiper.scss
Labels: 📁 documentation, ✏️ markup, 🖌️css styling

#108 Fix:signup페이지 리펙토링
  src/components/input/_input.scss
  src/components/input/input.js
  src/pages/signup/_signup.scss
  src/pages/signup/index.html
  src/pages/signup/signup.js
Labels: 🛠️ enhancement

#110 Style: 헤더 컴포넌트 로고 사이즈 변경
  index.html
  main.js
  src/components/footer/footer.js
  src/components/header/_header.scss
  src/components/rendingbutton/rendingbutton.js
Labels: 🖌️css styling

#113 Docs: pocketbase 이미지 URL 반환 함수 파일 생성
  api/getPbImageURL.js
  api/pocketbase.js
Labels: 💾 database

#114 Fix: 이미지 url 함수 매개변수 default img로 변경
  api/getPbImageURL.js
Labels: 🛠️ enhancement

#118 스와이퍼 이미지 포켓베이스 데이터 바인딩
  src/components/banner/_banner.scss
  src/components/banner/banner.js
  src/components/card-1/card-1.js
  src/components/card-2/_card-2.scss
  src/components/card-2/card-2.js
  src/components/card-3/_card-3.scss
  src/components/card-3/card-3.js
  src/components/card-4/_card-4.scss
  src/components/card-4/card-4.js
  src/pages/main/_main.scss
  src/pages/main/index.html
  src/pages/main/main.js
  src/styles/pages/main/_promo.scss
  src/styles/pages/main/_section.scss
  src/styles/pages/main/_swiper.scss
Labels: 💾 database

#119 Fix: signup 페이지 반응형 완벽!구현!
  src/components/input/_input.scss
  src/pages/signup/_signup.scss
  src/pages/signup/index.html
Labels: 🖌️css styling

#117 카드1 컴포넌트 - 반응형 수정 및 랜딩 페이지 - 스와이퍼 데이터 바인딩, 페이지 이동 함수 구현
  index.html
  main.js
  src/components/card-1/_card-1.scss
  src/components/profile/_profile.scss
  src/components/profile/profile.js
  src/pages/profile/_profile.scss
  src/pages/profile/index.html
  src/pages/profile/main.js
  src/styles/scss/_mixins.scss
  src/styles/scss/_variables.scss
  src/styles/style.scss
Labels: 🛠️ enhancement, 🖌️css styling

#121 Feat: 로그인 페이지
  src/pages/login/_login.scss
  src/pages/login/index.html
  src/pages/login/login.js
Labels: ✏️ markup, 🖌️css styling

#125 Feature/profile: 프로필 변경 UI 기능 구현
  main.js
  src/pages/profile/_profile.scss
  src/pages/profile/index.html
  src/pages/profile/main.js
Labels: 🛠️ enhancement, 🏃‍♀️ in progress

#126 Feat: 메인페이지 모달창 구현
  public/assets/modal_desktop.png
  public/assets/modal_mobile.png
  public/assets/modal_tablet.png
  src/pages/main/_main.scss
  src/pages/main/index.html
  src/pages/main/main.js
  src/pages/main/modal.js
  src/styles/pages/main/_modal.scss
Labels: ✏️ markup, 🖌️scss styling, 💻 feature

#129 Feat: 아이디,비밀번호,비밀번호 확인,이메일 칸 value 확인하여 validation 활성화
  src/components/input/_input.scss
  src/components/input/input.js
  src/pages/signup/signup.js
Labels: 🛠️ enhancement

#124 Feat: 아이디 찾기, 비밀번호 찾기
  src/pages/findID/_findID.scss
  src/pages/findID/findID.js
  src/pages/findID/index.html
  src/pages/findPW/_findPW.scss
  src/pages/findPW/findPW.js
  src/pages/findPW/index.html
Labels: ✏️ markup, 🖌️scss styling

#130 Docs: prettier config 파일 확장자 변경, detail 폴더 삭제
  prettier.config.cjs
  src/pages/detail/_detail.scss
  src/pages/detail/detail.js
  src/pages/detail/index.html
Labels: 📁 documentation

#136 Feat:체크박스 체크되었을때 버튼 활성화, 모두동의 버튼 체크시 아래 체크박스 모두 활성화
  src/pages/signup/_signup.scss
  src/pages/signup/index.html
  src/pages/signup/signup.js
Labels: 🛠️ enhancement

#137 pocketbase 로그인, 아이디 찾기, 비밀번호 찾기 연동
  src/pages/findID/findID.js
  src/pages/findPW/findPW.js
  src/pages/login/index.html
  src/pages/login/login.js
Labels: createData

#139 Test: build test
  src/components/banner/banner.js
  src/pages/search/recentSearch.js
  vite.config.js
Labels: build test

#143 Docs: 파일 삭제 및 경로 수정
  src/api/getPbImageURL.js
  src/components/banner/banner.js
  src/components/banner/index.html
  src/components/card-1/card-1.html
  src/components/card-1/card-1.js
  src/components/card-2/card-2.js
  src/components/card-2/index.html
  src/components/card-3/card-3.html
  src/components/card-3/card-3.js
  src/components/card-4/card-4.js
  src/components/card-4/index.html
  src/components/header/header.js
  src/components/input/index.html
  src/components/profile/index.html
  src/components/rendingbutton/index.html
  src/components/search/index.html
  src/pages/main/index.js
  src/pages/main/main.js
  src/pages/main/modules/index.js
  src/pages/main/modules/modal.js
  src/pages/main/modules/swiper.js
  src/pages/search/modules/ranking.js
  src/pages/search/modules/recentSearch.js
  src/pages/search/search.js
Labels: 📁 documentation

#134 Fix: 프로필 UI 변경 기능 수정
  src/pages/profile/_profile.scss
  src/pages/profile/main.js
Labels: 🛠️ enhancement

#146 Feat: 버튼클릭시 회원정보 포켓베이스로 전송시키기
  src/pages/signup/_signup.scss
  src/pages/signup/index.html
  src/pages/signup/signup.js
Labels: 🛠️ enhancement

#147 Feat: 메인페이지 시청중인 컨텐츠 구현
  src/components/card-2/_card-2.scss
  src/components/card-2/card-2.js
  src/components/card-3/card-3.js
  src/components/card-4/card-4.js
  src/components/header/header.js
  src/pages/main/index.html
  src/pages/main/modules/swiper.js
  src/pages/main/modules/watchedContent.js
  src/pages/search/search.js
  src/styles/pages/main/_section.scss
Labels: 💻 feature

#145 Feature/profile: 프로필 페이지 로고 누르면 메인으로 이동, 랜딩 페이지 애니메이션 추가
  index.html
  main.js
  src/pages/profile/_profile.scss
  src/pages/profile/main.js
Labels: 🛠️ enhancement, 💻 feature

#149 Fix: 헤더 불필요한 코드 삭제
  src/components/header/header.js
Labels: 🛠️ enhancement

#151 Feat: 서치페이지 검색결과가 없습니다 구현
  src/components/header/header.js
  src/components/search/_search.scss
  src/pages/search/_search.scss
  src/pages/search/index.html
  src/pages/search/modules/ranking.js
  src/pages/search/modules/recentSearch.js
  src/pages/search/modules/recentSearch2.js
  src/pages/search/search.js
Labels: 💻 feature

#154 Feat: 검색시 이미지 렌더링
  src/pages/search/_search.scss
  src/pages/search/_search.scss.orig
  src/pages/search/index.html
  src/pages/search/index.html.orig
  src/pages/search/modules/recentSearch.js
  src/pages/search/modules/recentSearch.js.orig
  src/pages/search/modules/recentSearch2.js
  src/pages/search/modules/renderInput.js
  src/pages/search/search.js
Labels: 📁 documentation, 💻 feature

#156 Feature/connect db
  public/assets/visibleId_1.png
  src/pages/findPW/findPW.js
  src/pages/findPW/index.html
  src/pages/login/_login.scss
  src/pages/login/index.html
  src/pages/login/login.js
Labels: ☑️ compleated, 💻 feature

#161 Feat: 프로필 모달창 구현
  src/components/header/_header.scss
  src/components/header/header.js
  src/pages/main/index.html
  src/pages/main/modules/index.js
  src/styles/pages/main/_modal.scss
Labels: 💻 feature

#159 Feature/profile: 프로필 페이지 데이터 코드 수정, 파비콘 추가 및 페이지 제목 변경
  index.html
  public/assets/favicon.ico
  src/pages/profile/_profile.scss
  src/pages/profile/main.js
Labels: 🛠️ enhancement, 🖌️scss styling, 💻 feature

#160 Fix: components card-4,search 반응형 수정
  src/components/card-4/_card-4.scss
  src/pages/search/_search.scss
  src/pages/search/index.html
  src/pages/search/search.js
Labels: 🖌️scss styling

#162 Style: 전체 페이지 파비콘 추가 및 제목 변경
  src/pages/findID/index.html
  src/pages/findPW/index.html
  src/pages/login/index.html
  src/pages/main/index.html
  src/pages/profile/index.html
  src/pages/search/index.html
  src/pages/signup/index.html
  src/styles/landing_lovecatcher.png
  src/styles/treasureHunt.png
Labels: 🖌️scss styling

#164 Feat: logout
  src/api/defaultAuth.js
  src/components/header/_header.scss
  src/components/header/header.js
Labels: 🏃‍♀️ in progress, 💻 feature

#170 헤더, 메인페이지 반응형 수정
  src/components/banner/_banner.scss
  src/components/header/_header.scss
  src/pages/main/index.html
  src/pages/main/modules/swiper.js
  src/pages/search/_search.scss
  src/pages/search/modules/renderInput.js
  src/styles/pages/main/_promo.scss
  src/styles/pages/main/_section.scss
Labels: 🖌️scss styling

#172 Feat: 메인페이지 애니메이션, 스와이퍼 슬라이드 멈춤 구현
  package-lock.json
  package.json
  src/components/banner/_banner.scss
  src/components/card-2/card-2.js
  src/components/card-3/card-3.js
  src/components/card-4/card-4.js
  src/components/header/header.js
  src/pages/main/index.html
  src/pages/main/main.js
  src/pages/main/modules/animation.js
  src/pages/main/modules/index.js
  src/pages/main/modules/swiper.js
  src/pages/main/modules/watchedContent.js
  src/styles/pages/main/_modal.scss
  src/styles/pages/main/_swiper.scss
Labels: 💻 feature

#174 Feat: 회원탈퇴 클릭시 포켓베이스 에 일치하는 아이디 삭제
  src/components/header/header.js
  src/pages/search/_search.scss
Labels: 🛠️ enhancement

#173 Fix: 프로필 첫 클릭 시 페이지 이동, 모바일 그리드 수정, 스타일링 수정
  src/pages/profile/_profile.scss
  src/pages/profile/main.js
Labels: 🛠️ enhancement

#179 Feature/logout
  src/components/header/_header.scss
  src/components/header/header.js
  src/pages/login/login.js
Labels: 🛠️ enhancement

#183 Fix: 프로필 페이지 클릭 이벤트 재수정, 랜딩 페이지 js에 코드 추가
  main.js
  src/pages/profile/main.js
Labels: 🛠️ enhancement

#182 Feat: 로딩창구현
  public/assets/loading.gif
  src/components/loading/_loading.scss
  src/components/loading/loading.js
  src/pages/main/index.html
  src/pages/main/modules/index.js
  src/pages/main/modules/swiper.js
Labels: 💻 feature

#184 Fix: 랜딩 페이지 스와이퍼 반응형 수정
  main.js
  src/styles/style.scss
Labels: 🛠️ enhancement, 🖌️scss styling

#185 Update README.md
  README.md
Labels: 🛠️ enhancement

#186 Feat: 로그아웃 모달 반응형
  src/components/header/_header.scss
Labels: 🖌️scss styling

#188 Fix: header.js await 문제 해결
  src/components/header/header.js
Labels: 🛠️ enhancement

#192 Fix: 랜딩 페이지에 로딩 추가
  index.html
  main.js
Labels: 🖌️scss styling

#196 Fix: 빌드 시 전역 오류, 헤더 이미지 경로 수정
  src/components/header/header.js
  src/pages/profile/main.js
  src/pages/search/_search.scss
  vite.config.js
Labels: ⚠️ bug

#194 Feat: 로그아웃 모달 수정
  src/components/header/_header.scss
  src/components/header/header.js
  src/pages/findID/_findID.scss
  src/pages/findID/findID.js
  src/pages/findPW/_findPW.scss
  src/pages/findPW/findPW.js
  src/pages/login/login.js
Labels: 🛠️ enhancement

#198 Fix: 유저생성시 이름 name 레코드에 username 데이터 바인딩
  src/pages/signup/signup.js
Labels: 🛠️ enhancement

#199 Fix: 애니메이션 수정, 로드시 페이지 상위로 고정
  src/components/header/_header.scss.orig
  src/components/header/header.js.orig
  src/components/loading/loading.js
  src/pages/main/main.js
  src/pages/main/modules/animation.js
Labels: ⚠️ bug

#201 Feature/refactor main
  src/components/loading/loading.js
  src/pages/search/modules/renderInput.js
Labels: ⚠️ bug

#205 Feat: 로그인 validation 수정
  src/pages/login/login.js
Labels: 🛠️ enhancement

#208 Test: 빌드 테스트 및 로그인 페이지 auth 정보 초기화
  src/pages/login/login.js
Labels: 🛠️ enhancement, build test

#209 Style: 기능 gif 첨부
  README.md
Labels: 🖌️scss styling

#213 Update: 배포 사이트 추가 및 목차 링크 수정
  README.md
Labels: 🛠️ enhancement
